Repository neurostuff/NiMARE, pull requests merged in 2022-06, with the labels that each got.

#689 Fix tag-name issue in update-changelog workflow
  .github/workflows/update-changelog.yml
Labels: documentation

#685 Optimize numpy operations in MKDADensity Estimator and (M)KDAKernel
  .zenodo.json
  docs/api.rst
  docs/conf.py
  nimare/meta/cbma/mkda.py
  nimare/meta/kernel.py
  nimare/meta/utils.py
  nimare/utils.py
Labels: refactoring, cbma

#695 Add PAT to automatically commit release notes to `CHANGELOG.md`
  .github/workflows/update-changelog.yml
Labels: documentation

#699 Add warning when coordinates dataset contains both positive and negative z_stats
  nimare/dataset.py
  nimare/tests/test_dataset.py
  nimare/transforms.py
Labels: enhancement, cbma

#691 Add parameter estimate standard error to IBMA results
  docs/outputs.rst
  nimare/meta/ibma.py
  nimare/tests/test_meta_ibma.py
  setup.cfg
Labels: enhancement, ibma

#701 Fix CHANGELOG formatting issues
  .github/workflows/update-changelog.yml
  CHANGELOG.md
Labels: documentation

#708 Add quotes around commit message in YAML file
  .github/workflows/update-changelog.yml
Labels: ignore-for-release

#712 Add citation information to documentation
  README.md
  docs/index.rst
  docs/references.bib
  nimare/workflows/ale.py
  nimare/workflows/conperm.py
  nimare/workflows/macm.py
  nimare/workflows/scale.py
Labels: documentation

#706 Add a glossary page to the documentation
  docs/glossary.rst
  docs/index.rst
  nimare/meta/ibma.py
Labels: documentation

#715 Use beta maps in PermutedOLS instead of z maps
  nimare/meta/ibma.py
Labels: bug, ibma

#662 Remove extraneous `copy()` statements
  nimare/meta/cbma/ale.py
  nimare/meta/cbma/base.py
  nimare/meta/cbma/mkda.py
Labels: refactoring

#703 Add information about maintaining NiMARE to developer's guide
  docs/dev_guide.rst
Labels: documentation, maintenance

#722 Pin minimum version of pandas
  setup.cfg
Labels: maintenance
