Repository neurostuff/NiMARE, pull requests merged in 2022-08, with the labels that each got.

#733 Switch from face+edge connectivity to face-only
  docs/cbma.rst
  nimare/diagnostics.py
  nimare/meta/cbma/base.py
  nimare/meta/cbma/mkda.py
Labels: cbma, breaking-change

#740 Remove conperm and scale CLI workflows
  docs/api.rst
  nimare/cli.py
  nimare/tests/test_workflows.py
  nimare/tests/utils.py
  nimare/workflows/__init__.py
  nimare/workflows/conperm.py
  nimare/workflows/scale.py
Labels: ibma, cbma, breaking-change

#741 Append the top 3 words to LDA topic names
  nimare/annotate/lda.py
Labels: enhancement

#743 Fix import in download_neurosynth example
  examples/01_datasets/02_download_neurosynth.py
Labels: documentation
