Repository neurostuff/NiMARE, pull requests merged in 2022-05, with the labels that each got.

#675 Simplify organization of base classes
  docs/api.rst
  nimare/base.py
  nimare/correct.py
  nimare/decode/base.py
  nimare/decode/continuous.py
  nimare/decode/discrete.py
  nimare/diagnostics.py
  nimare/meta/cbma/ale.py
  nimare/meta/cbma/base.py
  nimare/meta/cbma/mkda.py
  nimare/meta/ibma.py
  nimare/meta/kernel.py
  nimare/transforms.py
  nimare/utils.py
Labels: refactoring

#680 Note why we don't implement TFCE in NiMARE (currently)
  docs/cbma.rst
  docs/references.bib
Labels: documentation

#681 Dropping the memory-mapping option for Estimators and kernel transformers
  nimare/decode/continuous.py
  nimare/meta/cbma/ale.py
  nimare/meta/cbma/base.py
  nimare/meta/cbma/mkda.py
  nimare/meta/kernel.py
  nimare/meta/utils.py
  nimare/tests/test_meta_ale.py
  nimare/tests/test_meta_kernel.py
  nimare/tests/test_meta_mkda.py
Labels: refactoring

#682 Optimize locating coordinates in convert_neurosynth_to_dataset
  nimare/io.py
Labels: refactoring

#676 Reduce memory usage of `KernelTransformer.transform` and `meta.utils.compute_kda_ma`
  nimare/meta/cbma/base.py
  nimare/meta/cbma/mkda.py
  nimare/meta/kernel.py
  nimare/meta/utils.py
  nimare/tests/utils.py
  setup.cfg
Labels: refactoring

#686 Change code of conduct enforcer to James Kent
  CODE_OF_CONDUCT.md
Labels: community, ignore-for-release

#679 Refactor Correctors and remove statsmodels requirement
  docs/api.rst
  docs/cbma.rst
  docs/references.bib
  examples/02_meta-analyses/05_plot_correctors.py
  nimare/correct.py
  nimare/decode/discrete.py
  nimare/meta/cbma/mkda.py
  nimare/stats.py
  nimare/tests/test_meta_mkda.py
  setup.cfg
Labels: refactoring, correct, breaking-change, maintenance

#688 Automatically update `CHANGELOG.md` for prereleases as well
  .github/workflows/update-changelog.yml
Labels: documentation
