Repository neurostuff/NiMARE, pull requests merged in 2023-05, with the labels that each got.

#794 Unpin numpy version
  setup.cfg
Labels: maintenance

#793 Replace `_get_clusters_table` with nilearn's `get_clusters_table`
  nimare/diagnostics.py
  nimare/utils.py
  setup.cfg
Labels: maintenance

#796 Support Python 3.11
  .github/workflows/testing.yml
  docs/installation.rst
  setup.cfg
Labels: maintenance

#721 [ENH] add Coordinate Based Meta Regression
  .github/workflows/testing.yml
  docs/api.rst
  examples/01_datasets/05_plot_nimads.py
  examples/02_meta-analyses/11_plot_cbmr.py
  nimare/correct.py
  nimare/meta/cbmr.py
  nimare/meta/models.py
  nimare/resources/references.bib
  nimare/results.py
  nimare/tests/conftest.py
  nimare/tests/test_meta_cbmr.py
  nimare/tests/utils.py
  nimare/transforms.py
  nimare/utils.py
  setup.cfg
Labels: enhancement, cbma

#804 Add Corrector and Diagnostics attributes to MetaResult object
  docs/outputs.rst
  examples/02_meta-analyses/08_plot_cbma_subtraction_conjunction.py
  examples/02_meta-analyses/10_plot_cbma_workflow.py
  nimare/correct.py
  nimare/diagnostics.py
  nimare/results.py
  nimare/tests/test_diagnostics.py
  nimare/tests/test_workflows.py
  nimare/workflows/ale.py
  nimare/workflows/cbma.py
Labels: enhancement

#807 Add NiMAREBase features to the Corrector base class
  nimare/correct.py
Labels: enhancement

#802 Add `reports` module
  docs/api.rst
  docs/outputs.rst
  examples/02_meta-analyses/10_plot_cbma_workflow.py
  nimare/__init__.py
  nimare/diagnostics.py
  nimare/reports/__init__.py
  nimare/reports/base.py
  nimare/reports/default.yml
  nimare/reports/figures.py
  nimare/reports/report.tpl
  nimare/tests/test_reports.py
  nimare/tests/test_workflows.py
  nimare/workflows/cbma.py
  setup.cfg
Labels: enhancement
